FROM apache/airflow:2.10.3-python3.11

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    gcc \
    python3-full \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    libcurl4-openssl-dev \
    openjdk-17-jre-headless \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY howard /opt/howard

RUN chown -R airflow /opt/howard


COPY airflow/requirements.txt /opt/airflow/requirements.txt
COPY airflow/dags /opt/airflow/dags
COPY airflow/scripts /opt/airflow/scripts
COPY airflow/plugins /opt/airflow/plugins

USER airflow

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
# Устанавливаем HOWARD и зависимости (от airflow)
RUN pip install --no-cache-dir /opt/howard
RUN pip install --no-cache-dir -r /opt/airflow/requirements.txt